"""Add personas and documents

Revision ID: 32f319ff033f
Revises: 73a8c9612dc5
Create Date: 2026-03-21 07:55:44.765659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '32f319ff033f'
down_revision: Union[str, Sequence[str], None] = '73a8c9612dc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chatsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chatsession', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'You are a helpful AI assistant.'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatsession', schema=None) as batch_op:
        batch_op.drop_column('system_prompt')

    op.drop_table('document')
    # ### end Alembic commands ###
